spring.application.name=Fraud-detection-Pipeline

spring.datasource.url=jdbc:mysql://localhost:3306/pipeline-db
spring.datasource.username=root
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.cache.type = caffeine

fraud.amountThreshold = 20000000
fraud.geoAllowed = NG,GB,NZ,NL,AU,FR,DE,CA
fraud.blacklistCards = 4111111111111111,4000000000000002
